### ISSUE TITLE
申请加入索引: 云南大学镜像站

### ISSUE THREAD

**Issue by STRRL** [lework/lemonitor#3]
地址 [mirrors.ynu.edu.cn](http://mirrors.ynu.edu.cn), 上游为 tuna.

出口带宽主要在教育网.

目前已镜像：

- arch4edu
- archlinux 
- archlinuxarm
- archlinuxcn
- blackarch
- centos
- debian-cd
- debian-multimedia
- debian-nonfree
- debian-security
- debian
- deepin-cd
- deepin
- docker-ce
- fedora
- kali-images
- kali-security
- kali
- raspbian
- steamos
- ubuntu-cdimage
- ubuntu

**Comment by lework** [comment]
@STRRL 非常感谢提供，已添加。
