### ISSUE TITLE
我也做了个一模一样的列表…

### ISSUE THREAD

**Issue by skys215** [lework/lemonitor#5]
我还注册了个域名guoneiyuan.com。

要是资源一样的话，我把域名重定向或反代到你这里吧，如何？

如果你要域名的话，我也可以给你。

**Comment by lework** [comment]
这个到不需要了，不过还是谢谢。

**Comment by skys215** [comment]
能加*.googleapis.com之类的代理地址上去吗

**Comment by lework** [comment]
这类前端的资源，国内有做代理或者同步的，我添加了几个常用的。https://mirrors.leops.cn/#/usage
