### ISSUE TITLE
阿里云镜像问题

### ISSUE THREAD

**Issue by zidekuls** [lework/lemonitor#6]
你好，我搜索docker，点击结果中的阿里云镜像站点，跳转到的不是具体软件的下载界面。
还有一个开源数据库连接软件dbeaver，不知道有没有镜像下载站。谢谢。

**Comment by lework** [comment]
是这样的，目前只做了资源对应的镜像站点，具体的路径还需要在站点中搜索，dbeaver这个软件在github上也有，可以使用 https://mirrors.leops.cn/#/usage  github代理下载安装包
